### ISSUE TITLE
Type match error with `mir_llvm` lib

### ISSUE THREAD

**Issue by adrienluitot** [Kreijstal/OpenVAF#2]
When compiling `mir_llvm` I had a type match error.

```
error[E0308]: mismatched types
   --> openvaf/mir_llvm/src/lib.rs:528:17
    |
525 |             if llvm_sys::analysis::LLVMVerifyModule(
    |                ------------------------------------ arguments to this function are incorrect
...
528 |                 out_message,
    |                 ^^^^^^^^^^^ expected `*mut *mut u8`, found `*mut i8`
    |
    = note: expected raw pointer `*mut *mut u8`
               found raw pointer `*mut i8`
```

I fixed it by changing `openvaf/mir_llvm/src/lib.rs` line 524 from:
`let mut out_message: *mut i8 = std::ptr::null_mut();`
to:
`let mut out_message: *mut u8 = std::ptr::null_mut();`
(signed to unsigned)

**Comment by Kreijstal** [comment]
It's weird that CI didn't catch that one, on archlinux it seems to compile without problems, but pointers should be always positive.. 
I'll try to fiddle with it when I have time

**Comment by adrienluitot** [comment]
It's weird indeed, maybe your compiler achieve to cast it... I don't know.
Anyway the fix is easy, and as you said pointer shouldn't be negative anyway.

**Comment by adrienluitot** [comment]
I think the best solution is to use `c_char` as I did in adb199a.
I don't know why but `u8` would work on Linux arm64, but wouldn't work on MacOS (which needs the `i8`).
But `c_char` works on both. Also it seems to be the right type according to the doc: https://tombebbington.github.io/llvm-rs/llvm_sys/analysis/fn.LLVMVerifyModule.html
